### ISSUE TITLE
issue when add  SPFakeBarView

### ISSUE THREAD

**Issue by dverdugo85** [IvanVorobei/SparrowKit#1]
'SPFakeBarView' initializer is inaccessible due to 'internal' protection level

![image](https://user-images.githubusercontent.com/5117517/49606789-0ed20400-f973-11e8-8bb4-7eeb51f94755.png)

**Comment by dverdugo85** [comment]
not update yet

![image](https://user-images.githubusercontent.com/5117517/49608214-d2080c00-f976-11e8-8af6-8aa097ab19a3.png)

**Comment by IvanVorobei** [comment]
@dverdugo85 please, try 'pod update'

**Comment by IvanVorobei** [comment]
Ahahaha)) Sory, friend) Now I am fix it))

**Comment by IvanVorobei** [comment]
@dverdugo85 I am updated now to `1.0.8` version, please, use `pod update`

**Comment by dverdugo85** [comment]
@IvanVorobei  not work yet!!! regards!!

**Comment by dverdugo85** [comment]
<img width="545" alt="captura de pantalla 2018-12-06 a la s 19 19 56" src="https://user-images.githubusercontent.com/5117517/49615365-1e117b80-f98c-11e8-8c90-00fa272b3b48.png">

**Comment by IvanVorobei** [comment]
@dverdugo85 I am update Readme in project page. Thanks

**Comment by halilyuce** [comment]
I have same problem for "NotificationsViewController.setNavigationTitle("Title", style: .large)"

'setNavigationTitle' is inaccessible due to 'internal' protection level

**Comment by IvanVorobei** [comment]
You should use other code. Please, see readme file

**Comment by halilyuce** [comment]
> You should use other code. Please, see readme file

other code ? I reviewed readme file but code is same with my code :/

`Set navigation title for small or large style:

controller.setNavigationTitle("Title", style: .large)`

Do I miss something ?

`import UIKit
import CoreData
import SideMenu
import SparrowKit

class NotificationsViewController: UIViewController {
    var avatarLeft = String()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        let controller = NotificationsViewController()
        controller.setNavigationTitle("Title", style: .large)`

**Comment by IvanVorobei** [comment]
@halilyuce sorry
I confused where I answer. The error is really there. I will fix it in the next version. excuse me

**Comment by halilyuce** [comment]
> @halilyuce sorry
> I confused where I answer. The error is really there. I will fix it in the next version. excuse me

Thanks :) Some extensions are working well but some extensions are not working. I will eagerly await the next version, have a good day :)

**Comment by IvanVorobei** [comment]
@halilyuce I am release new version `1.4`. Sorry for delay and thanks for your help!
