### ISSUE TITLE
'xxxx' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by libern** [IvanVorobei/SparrowKit#3]
![image](https://user-images.githubusercontent.com/1830640/51738507-4daa4d80-20ca-11e9-92eb-b70b51540662.png)
![image](https://user-images.githubusercontent.com/1830640/51738538-5e5ac380-20ca-11e9-93b4-2ebcf46c04be.png)

**Comment by IvanVorobei** [comment]
Thanks! Soon I am upload new example. Real bug

**Comment by IvanVorobei** [comment]
@libern please update pods, I am publish new version
