### ISSUE TITLE
'bottomYPosition' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by libern** [IvanVorobei/SparrowKit#4]
![image](https://user-images.githubusercontent.com/1830640/51787021-908e2300-21a7-11e9-8bf8-bd5697864b86.png)
![image](https://user-images.githubusercontent.com/1830640/51787040-d0550a80-21a7-11e9-95b7-0195e1376fe6.png)

**Comment by libern** [comment]
Could you add "public" to all your extensions?

**Comment by IvanVorobei** [comment]
Fixed it in `1.4.4` version, please, update
