### ISSUE TITLE
FakeNavBar Change height and background color.

### ISSUE THREAD

**Issue by mcg95** [IvanVorobei/SparrowKit#5]
Hi,

I am currently using SPStorkController and using SparrowKit for the fake Nav Bar. Is there anyway I can make the height of the nav bar smaller? Also can I change the background color of it? 

        self.navBar.elementsColor = ColorCodes.ThemeBlue
        self.navBar.backgroundColor = ColorCodes.ThemeBlue

I used that code. Only the element color changed though. The background is still the same.

**Comment by IvanVorobei** [comment]
About height:

For change style see property `style` of `SPNavigationTitleStyle`. You can set `.small`. Also you can set custom height, use property `height`. 

About color:

View use `UIVisualEffectView` of background. You need add subview with equal frame for colorise nav bar.
