### ISSUE TITLE
I can't use SParrowKit Extensions

### ISSUE THREAD

**Issue by syedrazackimran** [IvanVorobei/SparrowKit#8]
Value of type 'UIImageView?' has no member 'downloadedFrom'

after I update SparrowKit Pod. I'm facing a lot of error. before I used swift 4.2, now I update to swift 5 also update you pod, suddenly I'm facing lots of error. previously UIExtenstion I used now I can't 

for eg:
UIImageViewExtension : downlaodedFrom -> download image from the server , now I can't use it
i'm getting `Value of type 'UIImageView?' has no member 'downloadedFrom'`

UIViewExtension: round() -> i am facing  `'round' is inaccessible due to 'internal' protection level`

**Comment by IvanVorobei** [comment]
For now I am not support `SparrowKit` for pod. I am recommend you download source folder and add files to your project.

I stopped supporting SparrowKit because I noticed that the library is not being used of users.
